package org.ai.auth.model;

import java.util.Date;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.ID
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.SYSTEM
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    private String system;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.NAME
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.DESC_EN
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    private String descEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.DESC_CN
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    private String descCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.UPDATED_DATE
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.CREATED_DATE
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    private Date createdDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.ID
     *
     * @return the value of user_role.ID
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.ID
     *
     * @param id the value for user_role.ID
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.SYSTEM
     *
     * @return the value of user_role.SYSTEM
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public String getSystem() {
        return system;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.SYSTEM
     *
     * @param system the value for user_role.SYSTEM
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public void setSystem(String system) {
        this.system = system == null ? null : system.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.NAME
     *
     * @return the value of user_role.NAME
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.NAME
     *
     * @param name the value for user_role.NAME
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.DESC_EN
     *
     * @return the value of user_role.DESC_EN
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public String getDescEn() {
        return descEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.DESC_EN
     *
     * @param descEn the value for user_role.DESC_EN
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public void setDescEn(String descEn) {
        this.descEn = descEn == null ? null : descEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.DESC_CN
     *
     * @return the value of user_role.DESC_CN
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public String getDescCn() {
        return descCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.DESC_CN
     *
     * @param descCn the value for user_role.DESC_CN
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public void setDescCn(String descCn) {
        this.descCn = descCn == null ? null : descCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.UPDATED_DATE
     *
     * @return the value of user_role.UPDATED_DATE
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.UPDATED_DATE
     *
     * @param updatedDate the value for user_role.UPDATED_DATE
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.CREATED_DATE
     *
     * @return the value of user_role.CREATED_DATE
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.CREATED_DATE
     *
     * @param createdDate the value for user_role.CREATED_DATE
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
}