package org.ai.sso.model;

import java.util.Date;

public class UserResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_resource.ID
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_resource.NAME
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_resource.DESC_EN
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    private String descEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_resource.DESC_CN
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    private String descCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_resource.PATH
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_resource.ACTION
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    private String action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_resource.UPDATED_DATE
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_resource.CREATED_DATE
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    private Date createdDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_resource.ID
     *
     * @return the value of user_resource.ID
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_resource.ID
     *
     * @param id the value for user_resource.ID
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_resource.NAME
     *
     * @return the value of user_resource.NAME
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_resource.NAME
     *
     * @param name the value for user_resource.NAME
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_resource.DESC_EN
     *
     * @return the value of user_resource.DESC_EN
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public String getDescEn() {
        return descEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_resource.DESC_EN
     *
     * @param descEn the value for user_resource.DESC_EN
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public void setDescEn(String descEn) {
        this.descEn = descEn == null ? null : descEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_resource.DESC_CN
     *
     * @return the value of user_resource.DESC_CN
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public String getDescCn() {
        return descCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_resource.DESC_CN
     *
     * @param descCn the value for user_resource.DESC_CN
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public void setDescCn(String descCn) {
        this.descCn = descCn == null ? null : descCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_resource.PATH
     *
     * @return the value of user_resource.PATH
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_resource.PATH
     *
     * @param path the value for user_resource.PATH
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_resource.ACTION
     *
     * @return the value of user_resource.ACTION
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_resource.ACTION
     *
     * @param action the value for user_resource.ACTION
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_resource.UPDATED_DATE
     *
     * @return the value of user_resource.UPDATED_DATE
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_resource.UPDATED_DATE
     *
     * @param updatedDate the value for user_resource.UPDATED_DATE
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_resource.CREATED_DATE
     *
     * @return the value of user_resource.CREATED_DATE
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_resource.CREATED_DATE
     *
     * @param createdDate the value for user_resource.CREATED_DATE
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
}