package org.ai.auth.dao;

import java.util.List;
import org.ai.auth.model.UserAuthorization;
import org.ai.auth.model.UserAuthorizationExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserAuthorizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorization
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    int countByExample(UserAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorization
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    int deleteByExample(UserAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorization
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    @Delete({
        "delete from user_authorization",
        "where USER_ID = #{userId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorization
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    @Insert({
        "insert into user_authorization (USER_ID, USER_LOGIN_NAME, ",
        "PASSWORD, USER_FIRST_NAME, ",
        "USER_LAST_NAME, LAST_LOGIN, ",
        "LAST_LOGIN_IP, LAST_LOGIN_SYSTEM, ",
        "UPDATED_DATE, CREATED_DATE)",
        "values (#{userId,jdbcType=INTEGER}, #{userLoginName,jdbcType=CHAR}, ",
        "#{password,jdbcType=CHAR}, #{userFirstName,jdbcType=CHAR}, ",
        "#{userLastName,jdbcType=CHAR}, #{lastLogin,jdbcType=TIMESTAMP}, ",
        "#{lastLoginIp,jdbcType=CHAR}, #{lastLoginSystem,jdbcType=CHAR}, ",
        "#{updatedDate,jdbcType=TIMESTAMP}, #{createdDate,jdbcType=TIMESTAMP})"
    })
    int insert(UserAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorization
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    int insertSelective(UserAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorization
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    List<UserAuthorization> selectByExample(UserAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorization
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    @Select({
        "select",
        "USER_ID, USER_LOGIN_NAME, PASSWORD, USER_FIRST_NAME, USER_LAST_NAME, LAST_LOGIN, ",
        "LAST_LOGIN_IP, LAST_LOGIN_SYSTEM, UPDATED_DATE, CREATED_DATE",
        "from user_authorization",
        "where USER_ID = #{userId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    UserAuthorization selectByPrimaryKey(Integer userId);

    @Select({
            "select",
            "USER_ID, USER_LOGIN_NAME, PASSWORD, USER_FIRST_NAME, USER_LAST_NAME, LAST_LOGIN, ",
            "LAST_LOGIN_IP, LAST_LOGIN_SYSTEM, UPDATED_DATE, CREATED_DATE",
            "from user_authorization",
            "where USER_LOGIN_NAME = #{loginName,jdbcType=CHAR}"
    })
    @ResultMap("BaseResultMap")
    UserAuthorization selectByLoginName(String loginName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorization
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserAuthorization record, @Param("example") UserAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorization
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    int updateByExample(@Param("record") UserAuthorization record, @Param("example") UserAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorization
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    int updateByPrimaryKeySelective(UserAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authorization
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    @Update({
        "update user_authorization",
        "set USER_LOGIN_NAME = #{userLoginName,jdbcType=CHAR},",
          "PASSWORD = #{password,jdbcType=CHAR},",
          "USER_FIRST_NAME = #{userFirstName,jdbcType=CHAR},",
          "USER_LAST_NAME = #{userLastName,jdbcType=CHAR},",
          "LAST_LOGIN = #{lastLogin,jdbcType=TIMESTAMP},",
          "LAST_LOGIN_IP = #{lastLoginIp,jdbcType=CHAR},",
          "LAST_LOGIN_SYSTEM = #{lastLoginSystem,jdbcType=CHAR},",
          "UPDATED_DATE = #{updatedDate,jdbcType=TIMESTAMP},",
          "CREATED_DATE = #{createdDate,jdbcType=TIMESTAMP}",
        "where USER_ID = #{userId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserAuthorization record);
}