package org.ai.sso.dao;

import java.util.List;
import org.ai.sso.model.UserRole;
import org.ai.sso.model.UserRoleExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    int countByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    int deleteByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    @Delete({
        "delete from user_role",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    @Insert({
        "insert into user_role (ID, SYSTEM, ",
        "NAME, DESC_EN, DESC_CN, ",
        "UPDATED_DATE, CREATED_DATE)",
        "values (#{id,jdbcType=INTEGER}, #{system,jdbcType=CHAR}, ",
        "#{name,jdbcType=CHAR}, #{descEn,jdbcType=CHAR}, #{descCn,jdbcType=CHAR}, ",
        "#{updatedDate,jdbcType=TIMESTAMP}, #{createdDate,jdbcType=TIMESTAMP})"
    })
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    List<UserRole> selectByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    @Select({
        "select",
        "ID, SYSTEM, NAME, DESC_EN, DESC_CN, UPDATED_DATE, CREATED_DATE",
        "from user_role",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    UserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserRole record, @Param("example") UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    int updateByExample(@Param("record") UserRole record, @Param("example") UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    @Update({
        "update user_role",
        "set SYSTEM = #{system,jdbcType=CHAR},",
          "NAME = #{name,jdbcType=CHAR},",
          "DESC_EN = #{descEn,jdbcType=CHAR},",
          "DESC_CN = #{descCn,jdbcType=CHAR},",
          "UPDATED_DATE = #{updatedDate,jdbcType=TIMESTAMP},",
          "CREATED_DATE = #{createdDate,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserRole record);
}