package org.ai.sso.dao;

import java.util.List;
import org.ai.sso.model.UserResource;
import org.ai.sso.model.UserResourceExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    int countByExample(UserResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    int deleteByExample(UserResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    @Delete({
        "delete from user_resource",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    @Insert({
        "insert into user_resource (ID, NAME, DESC_EN, ",
        "DESC_CN, PATH, ACTION, ",
        "UPDATED_DATE, CREATED_DATE)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=CHAR}, #{descEn,jdbcType=CHAR}, ",
        "#{descCn,jdbcType=CHAR}, #{path,jdbcType=CHAR}, #{action,jdbcType=CHAR}, ",
        "#{updatedDate,jdbcType=TIMESTAMP}, #{createdDate,jdbcType=TIMESTAMP})"
    })
    int insert(UserResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    int insertSelective(UserResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    List<UserResource> selectByExample(UserResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    @Select({
        "select",
        "ID, NAME, DESC_EN, DESC_CN, PATH, ACTION, UPDATED_DATE, CREATED_DATE",
        "from user_resource",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    UserResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserResource record, @Param("example") UserResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    int updateByExample(@Param("record") UserResource record, @Param("example") UserResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    int updateByPrimaryKeySelective(UserResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Mon May 09 15:09:09 CST 2016
     */
    @Update({
        "update user_resource",
        "set NAME = #{name,jdbcType=CHAR},",
          "DESC_EN = #{descEn,jdbcType=CHAR},",
          "DESC_CN = #{descCn,jdbcType=CHAR},",
          "PATH = #{path,jdbcType=CHAR},",
          "ACTION = #{action,jdbcType=CHAR},",
          "UPDATED_DATE = #{updatedDate,jdbcType=TIMESTAMP},",
          "CREATED_DATE = #{createdDate,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserResource record);
}